### ISSUE TITLE
new sandmanctl error after upgrading to 0.7.1

### ISSUE THREAD

**Issue by ghost** [jeffknupp/sandman#35]
pretty sure this just showed me the needed options in 0.7

```
$ sandmanctl
Traceback (most recent call last):
  File "/Users/jan/.virtualenvs/foo/bin/sandmanctl", line 52, in <module>
    sys.exit(main())
  File "/Users/jan/.virtualenvs/foo/bin/sandmanctl", line 48, in main
    activate(admin=True)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sandman/model/__init__.py", line 70, in activate
    db.metadata.reflect(bind=db.engine)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 780, in engine
    return self.get_engine(self.get_app())
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 797, in get_engine
    return connector.get_engine()
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 470, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 739, in apply_driver_hacks
    if info.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
```

**Comment by jeffknupp** [comment]
OK, this looks like an error constructing your URI. You need to include the database engine **plus the driver**. For example, if you connect to `mysql` using `mysql-connector-python`, you would start the URI `mysql+mysqlconnector://`. The list of connectors/engines can be found in the SQLAlchemy docs.
